# Generated by Django 5.2.8 on 2025-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=12)),
                ('address', models.CharField()),
                ('city', models.CharField(max_length=20)),
                ('collegename', models.CharField()),
            ],
        ),
    ]
