# Generated by Django 5.2.8 on 2025-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FNAME', models.CharField(max_length=50)),
                ('LNAME', models.CharField(max_length=50)),
                ('BIRTHDAY', models.DateField(blank=True, null=True)),
                ('GENDER', models.CharField(blank=True, max_length=10)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('PHONE', models.CharField(blank=True, max_length=10)),
                ('ADDRESS', models.CharField(blank=True, max_length=200)),
                ('CITY', models.CharField(blank=True, max_length=50)),
                ('COLLEGENAME', models.CharField(blank=True, max_length=100)),
                ('QUALIFICATION', models.CharField(blank=True, max_length=50)),
                ('BRANCH', models.CharField(blank=True, max_length=50)),
                ('PASSING_YEAR', models.CharField(blank=True, max_length=10)),
                ('TECHNOLOGY', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='contactform',
        ),
    ]
