# Generated by Django 5.2.8 on 2025-12-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_student_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EMAIL',
            field=models.EmailField(max_length=254),
        ),
    ]
