# Generated by Django 5.2.8 on 2025-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='QUALIFICATION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
