# Generated by Django 5.2.8 on 2025-12-13 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_alter_student_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ADDRESS',
        ),
        migrations.RemoveField(
            model_name='student',
            name='BIRTHDAY',
        ),
        migrations.RemoveField(
            model_name='student',
            name='BRANCH',
        ),
        migrations.RemoveField(
            model_name='student',
            name='GENDER',
        ),
        migrations.RemoveField(
            model_name='student',
            name='QUALIFICATION',
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='CITY',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='COLLEGENAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='PASSING_YEAR',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='PHONE',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='TECHNOLOGY',
            field=models.CharField(max_length=50),
        ),
    ]
