# Generated by Django 5.2.8 on 2025-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_remove_student_address_remove_student_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='ADDRESS',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='BIRTHDAY',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='BRANCH',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='GENDER',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='QUALIFICATION',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='CITY',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='COLLEGENAME',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='PASSING_YEAR',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='PHONE',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='TECHNOLOGY',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
