# Generated by Django 5.2.8 on 2025-12-24 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_remove_student_created_at_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('visiting', 'Visiting'), ('adjoining', 'Adjoining'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='visiting', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='visiting_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
