# Generated by Django 5.2.8 on 2025-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_student_joining_at_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('fullstack', 'Full Stack')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='remaining_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
