# Generated by Django 5.2.8 on 2026-03-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0010_followup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
