# Generated by Django 6.0.4 on 2026-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
