# Generated by Django 6.0.4 on 2026-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0015_student_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
